# Copyright (c) 08 March 2020 All rights reserved OneOfTheInfiniteMonkeys
# https://travis-ci.com
# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

php: 
  - 5.5

dist: trusty  

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    
script: phpunit --coverage-text
