# Travis CI Configuration File

# Tell Travis CI we're using PHP
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# As Travis CI build uses the Xenial dist by default, not Trusty apparently!
dist: trusty

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  #- 5.2
  # aliased to 5.3.29
  #- 5.3
  # aliased to a recent 5.4.x version
  #- 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

# optionally set up exclusions and allowed failures in the matrix
matrix:
#  exclude:
#    - php: hhvm
#      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

# Run test script commands.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors
  - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
